### PR TITLE
fix(platform-server): change repository url

### LINKED ISSUE #350: [bug] GitHub api url is not used everywhere
The GitHub url set on the main configuration page is not used everywhere throughout the application, which can cause a few bugs. For example the build fails because the [commit status service](https://github.com/bleenco/abstruse/blob/1e4c846c270ed8864750c4dd174705ca76dddb31/src/api/commit-status.ts#L13) does not use the right endpoint. 

This results in an error like the following: ```request to https://api.github.com/repos/:org/:repo/statuses/:sha failed with error code 401```

The other place I noticed the issue was in the [api service](https://github.com/bleenco/abstruse/blob/c0f442939206e7b31703e459aaf66b4f8404c0b2/src/app/services/api.service.ts#L181) file, but I have not noticed any issues caused by that, yet.

### PR DESCRIPTION
**Pull request by matthax**
fix(platform-server): change repository url

change status endpoint to use the configured repository.api_url

fix #350

### CODE REVIEW

**Comment by matthax** [comment]
I can't sign the CLA with the user I used to make the changes, it's not tied to a public github account.

**Comment by jkuri** [comment]
can you please squash commits, you can do it with
```sh
$ git rebase -i HEAD~3 && git push origin fix-commit-status -f
```
just mark bottom 2 commits with s (squash) and save, then edit the commit message to include only one.

**Comment by jkuri** [comment]
about CLA don't bother, I have intent to remove that anyway :)

**Comment by matthax** [comment]
I'm on the train, I will rebase as soon as I'm home. Sorry about that

**Comment by matthax** [comment]
Not sure why the build is failing, don't think it's related to my changes because it says it can't click a button.

**Comment by jkuri** [comment]
yes, protractor e2e tests sometimes fails and need to be restarted.

**Comment by matthax** [comment]
It appears I missed the setCompleteStatus in my changes. I will make the fix for that today and squash it with the other commit so I'm not making a mess out of the commit history.

**Pull request merged**
