### PR TITLE
feat: environment variables

### PR DESCRIPTION
**Pull request by jkuri**
This PR will close https://github.com/bleenco/abstruse/issues/486

### CODE REVIEW

**Comment by jkuri** [comment]
no, this pr is in progress.

**Comment by jkuri** [comment]
@belsakn this PR is ready to review when you have time.

**Review by irmana — APPROVED** [review]
This looks good to go in. We'd have to get some feedback from users...

**Comment by jkuri** [comment]
I checked this in action:

Screenshot 2021-01-13 at 16 23 14

and tried echo variable

Screenshot 2021-01-13 at 21 36 41

so I think its good. thanks for approval.

**Pull request merged**
