### PR TITLE
WIP: Codebase Clean Up

### PR DESCRIPTION
**Pull request by sabrehagen**
Hi,

Thanks for making a great product with Abstruse CI; it has become an integral part of my development workflow.

### Tasks For Completion
- [ ] Handle running containers [not found](https://user-images.githubusercontent.com/1094600/49029397-9774d580-f1f8-11e8-86d2-b211e154e4d4.png) on the Docker host
- [ ] Restore Docker multi-stage build
- [ ] Get CI Running Green

On November 30 and 31 I did a review of the codebase and performed a number of clean up and modernisation tasks. The changes were widespread, so I decided to test them for a while before submitting a pull request. I have been the code in this PR daily for the last 19 days. I've had no bugs arise in that time.

I have outlined the changes in the sections below.

### Re-order Dockerfile to optimise caching

I found it was far more convenient to supply the `docker-essential` abstruse files as part of the abstruse container. I [added these](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-3254677a7917c6c01f55212f86c57fbf) to the image. At 1.4 MB they are not a large increase to the container size.

Previously the source code was [added before](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-3254677a7917c6c01f55212f86c57fbfL24) the build dependencies. This meant that any time the source code changed, the dependencies must be reinstalled, adding a large delay to the build time unnecessary. I have reordered the Dockerfile so the most volatile files are [added later](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-3254677a7917c6c01f55212f86c57fbfR92) in the image, reducing build times.

### Remove Unused Declarations and Arguments

Throughout the codebase there were many [declarations](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-5c7073bff630176953f94f2b481baec1L53) and [arguments](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-b0c788b128da41d098f9b154b65b7285L174) that were never referenced in the code. Turning on [`noUnusedLocals`](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-e5e546dd2eb0351f813d63d1b39dbc48R12) and [`noUnusedParameters`](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-e5e546dd2eb0351f813d63d1b39dbc48R13). This makes for unnecessary reading for developers, as the code is completely redundant. As a best practice I have removed any unreferenced declarations.

Many unused declarations were in files that were (presumably) [automatically generated](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-9d9029cb96ddb9ea9b35c63a3d64eb03L55).

### Sort, Group, and Remove Unused Imports

The [TypeScript Hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero) plugin was used when saving files. It has [sorted and grouped](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-5c0488032b1ae3505fe37092459b8ddaR3) imports, and [removed unused imports](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-f5d6847681c108cb2d2fcaace93bf36bL3) as well.

### Remove redundant `new Promise`

Many places [throughout the codebase](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0faeadff2c25d3ce9ce4bf4416866eb4L24) an existing `Promsie` was wrapped with `new Promise`. I have removed instances of this to avoid mixed async paradigms, and remove extraneous closures, and reduce redundant code.

[1](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0faeadff2c25d3ce9ce4bf4416866eb4L24)
[2](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0faeadff2c25d3ce9ce4bf4416866eb4L31)
[3](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-44d52a0fbb92620b2b962bb206e00babL17)
[4](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-44d52a0fbb92620b2b962bb206e00babL38)
[5](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0e97f0f8805573e615fc24e54ab893feL5)
[6](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0e97f0f8805573e615fc24e54ab893feL18)
[7](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL7)
[8](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL19)
[9](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL31)
[10](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL43)
[11](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL55)
[12](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-2cfca7c3e538500c2ba59ecbf476ea2fL67)
[13](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-8076ba474fb008a688e4f854f83955b2L156)
[14](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0ca59862f8642a7a40d5047c799bdd1eL250)
[15](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-8076ba474fb008a688e4f854f83955b2L164)
[16](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-a52bea69d384e9d313e2997d9464d6a4L45)
[17](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-e1fdc38ece8441496f0fa814512ebd4eL24)

### Use Async/Await where possible

The codebase has many uses of async/await throughout already. I updated promises to async/await syntax where possible to make code more readable.

[1](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0ca59862f8642a7a40d5047c799bdd1eL23)
[2](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0ca59862f8642a7a40d5047c799bdd1eL174)
[3](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-0ca59862f8642a7a40d5047c799bdd1eL195)
[4](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-8076ba474fb008a688e4f854f83955b2R172)
[5](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-a52bea69d384e9d313e2997d9464d6a4R50)
[6](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-c39a5818238c0e8002957670553593b3R120)

### To be removed before PR acceptance:

[Image name](https://github.com/bleenco/abstruse/compare/master...stemn:develop#diff-1f881ac625e941eabeca294597e23858R1)

## Acceptance Criteria

Please let me know of any changes you'd like further clarified or reverted. When the PR is ready the commit log can be squashed to match the angular style guide.

### CODE REVIEW

**Comment by cooperaj** [comment]
> I have reordered the Dockerfile so the most volatile files are added later in the image, reducing build times.

You've also removed the multistage build of components and therefore introduced numerous large layers to the final image. Is there a reason for this?

**Comment by sabrehagen** [comment]
> > I have reordered the Dockerfile so the most volatile files are added later in the image, reducing build times.
> 
> You've also removed the multistage build of components and therefore introduced numerous large layers to the final image. Is there a reason for this?

This was unfinished workings. I'll restore the multistage build. Thanks.

**Comment by jkuri** [comment]
@sabrehagen looks like CI is failing. I am not going to merge anything that doesn't run green on our CI.

If you are willing to help on abstruse development, I am working hard on `2.0.0` release and a ton of tests are missing, please check: https://github.com/bleenco/abstruse/tree/2.0.0.

Here is preview of `2.0.0` branch, I created screenshots couple of minutes ago:
screenshot 2018-11-26 at 17 10 04
screenshot 2018-11-26 at 17 14 19

Let me know if you are willing to help me on that, your help is greatly appreciated and we can connect via Slack or something.

Nice regards, Jan

**Comment by sabrehagen** [comment]
> @sabrehagen looks like CI is failing. I am not going to merge anything that doesn't run green on our CI.

Certainly. Currently [the image](https://hub.docker.com/r/stemn/abstruse/) i'm trying to run is not found:

image

I have made a To Do list in my [original post](https://github.com/bleenco/abstruse/pull/437#issue-231770701) and added this.

> 
> If you are willing to help on abstruse development, I am working hard on `2.0.0` release and a ton of tests are missing, please check: https://github.com/bleenco/abstruse/tree/2.0.0.
> 

I saw this when digging through the forks :) It's looking very nice.

The changes I made to the front-end files were purely for `tslint` purposes i.e. removing unused imports, variables, and arguments. There was no functional change. I'm happy to revert the tslint rule and the front-end files to minimise merge conflicts if you'd like.

> 
> Let me know if you are willing to help me on that, your help is greatly appreciated and we can connect via Slack or something.
> 

Sure, I am willing to help. I joined your Slack too.

> Nice regards, Jan

Mutually, Jackson.

**Comment by jkuri** [comment]
Closing in favor of v2

**Pull request closed without merging**
